
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.ComponentModel;
using System.Linq;
using Softv.Providers;
using Softv.Entities;
using Globals;

/// <summary>
/// Class                   : Softv.BAL.Client.cs
/// Generated by            : Class Generator (c) 2014
/// Description             : Cliente_ApellidoBussines
/// File                    : Cliente_ApellidoBussines.cs
/// Creation date           : 04/05/2016
/// Creation time           : 01:30 p. m.
///</summary>
namespace Softv.BAL
{

    [DataObject]
    [Serializable]
    public class Cliente_Apellido
    {

        #region Constructors
        public Cliente_Apellido() { }
        #endregion

        /// <summary>
        ///Adds Cliente_Apellido
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public static int Add(Cliente_ApellidoEntity objCliente_Apellido)
        {
            int result = ProviderSoftv.Cliente_Apellido.AddCliente_Apellido(objCliente_Apellido);
            return result;
        }

        /// <summary>
        ///Delete Cliente_Apellido
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public static int Delete(long? Contrato)
        {
            int resultado = ProviderSoftv.Cliente_Apellido.DeleteCliente_Apellido(Contrato);
            return resultado;
        }

        /// <summary>
        ///Update Cliente_Apellido
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public static int Edit(Cliente_ApellidoEntity objCliente_Apellido)
        {
            int result = ProviderSoftv.Cliente_Apellido.EditCliente_Apellido(objCliente_Apellido);
            return result;
        }

        /// <summary>
        ///Get Cliente_Apellido
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<Cliente_ApellidoEntity> GetAll()
        {
            List<Cliente_ApellidoEntity> entities = new List<Cliente_ApellidoEntity>();
            entities = ProviderSoftv.Cliente_Apellido.GetCliente_Apellido();

            return entities ?? new List<Cliente_ApellidoEntity>();
        }

        /// <summary>
        ///Get Cliente_Apellido List<lid>
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<Cliente_ApellidoEntity> GetAll(List<int> lid)
        {
            List<Cliente_ApellidoEntity> entities = new List<Cliente_ApellidoEntity>();
            entities = ProviderSoftv.Cliente_Apellido.GetCliente_Apellido(lid);
            return entities ?? new List<Cliente_ApellidoEntity>();
        }

        /// <summary>
        ///Get Cliente_Apellido By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static Cliente_ApellidoEntity GetOne(long? Contrato)
        {
            Cliente_ApellidoEntity result = ProviderSoftv.Cliente_Apellido.GetCliente_ApellidoById(Contrato);

            return result;
        }

        /// <summary>
        ///Get Cliente_Apellido By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static Cliente_ApellidoEntity GetOneDeep(long? Contrato)
        {
            Cliente_ApellidoEntity result = ProviderSoftv.Cliente_Apellido.GetCliente_ApellidoById(Contrato);

            return result;
        }



        /// <summary>
        ///Get Cliente_Apellido
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<Cliente_ApellidoEntity> GetPagedList(int pageIndex, int pageSize)
        {
            SoftvList<Cliente_ApellidoEntity> entities = new SoftvList<Cliente_ApellidoEntity>();
            entities = ProviderSoftv.Cliente_Apellido.GetPagedList(pageIndex, pageSize);

            return entities ?? new SoftvList<Cliente_ApellidoEntity>();
        }

        /// <summary>
        ///Get Cliente_Apellido
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<Cliente_ApellidoEntity> GetPagedList(int pageIndex, int pageSize, String xml)
        {
            SoftvList<Cliente_ApellidoEntity> entities = new SoftvList<Cliente_ApellidoEntity>();
            entities = ProviderSoftv.Cliente_Apellido.GetPagedList(pageIndex, pageSize, xml);

            return entities ?? new SoftvList<Cliente_ApellidoEntity>();
        }


    }




    #region Customs Methods

    #endregion
}
