
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.ComponentModel;
using System.Linq;
using Softv.Providers;
using Softv.Entities;
using Globals;

/// <summary>
/// Class                   : Softv.BAL.Client.cs
/// Generated by            : Class Generator (c) 2014
/// Description             : RelPreguntaOpcMultsBussines
/// File                    : RelPreguntaOpcMultsBussines.cs
/// Creation date           : 27/04/2016
/// Creation time           : 05:19 p. m.
///</summary>
namespace Softv.BAL
{

    [DataObject]
    [Serializable]
    public class RelPreguntaOpcMults
    {

        #region Constructors
        public RelPreguntaOpcMults() { }
        #endregion

        /// <summary>
        ///Adds RelPreguntaOpcMults
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public static int Add(RelPreguntaOpcMultsEntity objRelPreguntaOpcMults)
        {
            int result = ProviderSoftv.RelPreguntaOpcMults.AddRelPreguntaOpcMults(objRelPreguntaOpcMults);
            return result;
        }

        /// <summary>
        ///Delete RelPreguntaOpcMults
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public static int Delete(int? IdPregunta)
        {
            int resultado = ProviderSoftv.RelPreguntaOpcMults.DeleteRelPreguntaOpcMults(IdPregunta);
            return resultado;
        }

        /// <summary>
        ///Update RelPreguntaOpcMults
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public static int Edit(RelPreguntaOpcMultsEntity objRelPreguntaOpcMults)
        {
            int result = ProviderSoftv.RelPreguntaOpcMults.EditRelPreguntaOpcMults(objRelPreguntaOpcMults);
            return result;
        }

        /// <summary>
        ///Get RelPreguntaOpcMults
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<RelPreguntaOpcMultsEntity> GetAll()
        {
            List<RelPreguntaOpcMultsEntity> entities = new List<RelPreguntaOpcMultsEntity>();
            entities = ProviderSoftv.RelPreguntaOpcMults.GetRelPreguntaOpcMults();

            List<PreguntaEntity> lPregunta = ProviderSoftv.Pregunta.GetPregunta(entities.Where(x => x.IdPregunta.HasValue).Select(x => x.IdPregunta.Value).ToList());
            lPregunta.ForEach(XPregunta => entities.Where(x => x.IdPregunta.HasValue).Where(x => x.IdPregunta == XPregunta.IdPregunta).ToList().ForEach(y => y.Pregunta = XPregunta));

            List<ResOpcMultsEntity> lResOpcMults = ProviderSoftv.ResOpcMults.GetResOpcMults(entities.Where(x => x.Id_ResOpcMult.HasValue).Select(x => x.Id_ResOpcMult.Value).ToList());
            lResOpcMults.ForEach(XResOpcMults => entities.Where(x => x.Id_ResOpcMult.HasValue).Where(x => x.Id_ResOpcMult == XResOpcMults.Id_ResOpcMult).ToList().ForEach(y => y.ResOpcMults = XResOpcMults));

            return entities ?? new List<RelPreguntaOpcMultsEntity>();
        }

        /// <summary>
        ///Get RelPreguntaOpcMults List<lid>
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<RelPreguntaOpcMultsEntity> GetAll(List<int> lid)
        {
            List<RelPreguntaOpcMultsEntity> entities = new List<RelPreguntaOpcMultsEntity>();
            entities = ProviderSoftv.RelPreguntaOpcMults.GetRelPreguntaOpcMults(lid);
            return entities ?? new List<RelPreguntaOpcMultsEntity>();
        }

        /// <summary>
        ///Get RelPreguntaOpcMults By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static RelPreguntaOpcMultsEntity GetOne(int? IdPregunta)
        {
            RelPreguntaOpcMultsEntity result = ProviderSoftv.RelPreguntaOpcMults.GetRelPreguntaOpcMultsById(IdPregunta);

            if (result.IdPregunta != null)
                result.Pregunta = ProviderSoftv.Pregunta.GetPreguntaById(result.IdPregunta);

            if (result.Id_ResOpcMult != null)
                result.ResOpcMults = ProviderSoftv.ResOpcMults.GetResOpcMultsById(result.Id_ResOpcMult);

            return result;
        }

        /// <summary>
        ///Get RelPreguntaOpcMults By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static RelPreguntaOpcMultsEntity GetOneDeep(int? IdPregunta)
        {
            RelPreguntaOpcMultsEntity result = ProviderSoftv.RelPreguntaOpcMults.GetRelPreguntaOpcMultsById(IdPregunta);

            if (result.IdPregunta != null)
                result.Pregunta = ProviderSoftv.Pregunta.GetPreguntaById(result.IdPregunta);

            if (result.Id_ResOpcMult != null)
                result.ResOpcMults = ProviderSoftv.ResOpcMults.GetResOpcMultsById(result.Id_ResOpcMult);

            return result;
        }

        public static List<RelPreguntaOpcMultsEntity> GetRelPreguntaOpcMultsByIdPregunta(int? IdPregunta)
        {
            List<RelPreguntaOpcMultsEntity> entities = new List<RelPreguntaOpcMultsEntity>();
            entities = ProviderSoftv.RelPreguntaOpcMults.GetRelPreguntaOpcMultsByIdPregunta(IdPregunta);
            return entities ?? new List<RelPreguntaOpcMultsEntity>();
        }

        public static List<RelPreguntaOpcMultsEntity> GetRelPreguntaOpcMultsById_ResOpcMult(int? Id_ResOpcMult)
        {
            List<RelPreguntaOpcMultsEntity> entities = new List<RelPreguntaOpcMultsEntity>();
            entities = ProviderSoftv.RelPreguntaOpcMults.GetRelPreguntaOpcMultsById_ResOpcMult(Id_ResOpcMult);
            return entities ?? new List<RelPreguntaOpcMultsEntity>();
        }



        /// <summary>
        ///Get RelPreguntaOpcMults
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<RelPreguntaOpcMultsEntity> GetPagedList(int pageIndex, int pageSize)
        {
            SoftvList<RelPreguntaOpcMultsEntity> entities = new SoftvList<RelPreguntaOpcMultsEntity>();
            entities = ProviderSoftv.RelPreguntaOpcMults.GetPagedList(pageIndex, pageSize);

            List<PreguntaEntity> lPregunta = ProviderSoftv.Pregunta.GetPregunta(entities.Where(x => x.IdPregunta.HasValue).Select(x => x.IdPregunta.Value).Distinct().ToList());
            lPregunta.ForEach(XPregunta => entities.Where(x => x.IdPregunta.HasValue).Where(x => x.IdPregunta == XPregunta.IdPregunta).ToList().ForEach(y => y.Pregunta = XPregunta));

            List<ResOpcMultsEntity> lResOpcMults = ProviderSoftv.ResOpcMults.GetResOpcMults(entities.Where(x => x.Id_ResOpcMult.HasValue).Select(x => x.Id_ResOpcMult.Value).Distinct().ToList());
            lResOpcMults.ForEach(XResOpcMults => entities.Where(x => x.Id_ResOpcMult.HasValue).Where(x => x.Id_ResOpcMult == XResOpcMults.Id_ResOpcMult).ToList().ForEach(y => y.ResOpcMults = XResOpcMults));

            return entities ?? new SoftvList<RelPreguntaOpcMultsEntity>();
        }

        /// <summary>
        ///Get RelPreguntaOpcMults
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<RelPreguntaOpcMultsEntity> GetPagedList(int pageIndex, int pageSize, String xml)
        {
            SoftvList<RelPreguntaOpcMultsEntity> entities = new SoftvList<RelPreguntaOpcMultsEntity>();
            entities = ProviderSoftv.RelPreguntaOpcMults.GetPagedList(pageIndex, pageSize, xml);

            List<PreguntaEntity> lPregunta = ProviderSoftv.Pregunta.GetPregunta(entities.Where(x => x.IdPregunta.HasValue).Select(x => x.IdPregunta.Value).Distinct().ToList());
            lPregunta.ForEach(XPregunta => entities.Where(x => x.IdPregunta.HasValue).Where(x => x.IdPregunta == XPregunta.IdPregunta).ToList().ForEach(y => y.Pregunta = XPregunta));

            List<ResOpcMultsEntity> lResOpcMults = ProviderSoftv.ResOpcMults.GetResOpcMults(entities.Where(x => x.Id_ResOpcMult.HasValue).Select(x => x.Id_ResOpcMult.Value).Distinct().ToList());
            lResOpcMults.ForEach(XResOpcMults => entities.Where(x => x.Id_ResOpcMult.HasValue).Where(x => x.Id_ResOpcMult == XResOpcMults.Id_ResOpcMult).ToList().ForEach(y => y.ResOpcMults = XResOpcMults));

            return entities ?? new SoftvList<RelPreguntaOpcMultsEntity>();
        }


    }




    #region Customs Methods

    #endregion
}
