
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.ComponentModel;
using System.Linq;
using Softv.Providers;
using Softv.Entities;
using Globals;

/// <summary>
/// Class                   : Softv.BAL.Client.cs
/// Generated by            : Class Generator (c) 2014
/// Description             : ServicioBussines
/// File                    : ServicioBussines.cs
/// Creation date           : 14/06/2016
/// Creation time           : 11:09 a. m.
///</summary>
namespace Softv.BAL
{

    [DataObject]
    [Serializable]
    public class Servicio
    {

        #region Constructors
        public Servicio() { }
        #endregion

        /// <summary>
        ///Adds Servicio
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public static int Add(ServicioEntity objServicio)
        {
            int result = ProviderSoftv.Servicio.AddServicio(objServicio);
            return result;
        }

        /// <summary>
        ///Delete Servicio
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public static int Delete(int? Clv_Servicio)
        {
            int resultado = ProviderSoftv.Servicio.DeleteServicio(Clv_Servicio);
            return resultado;
        }

        /// <summary>
        ///Update Servicio
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public static int Edit(ServicioEntity objServicio)
        {
            int result = ProviderSoftv.Servicio.EditServicio(objServicio);
            return result;
        }

        /// <summary>
        ///Get Servicio
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<ServicioEntity> GetAll()
        {
            List<ServicioEntity> entities = new List<ServicioEntity>();
            entities = ProviderSoftv.Servicio.GetServicio();

            return entities ?? new List<ServicioEntity>();
        }

        /// <summary>
        ///Get Servicio List<lid>
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<ServicioEntity> GetAll(List<int> lid)
        {
            List<ServicioEntity> entities = new List<ServicioEntity>();
            entities = ProviderSoftv.Servicio.GetServicio(lid);
            return entities ?? new List<ServicioEntity>();
        }

        /// <summary>
        ///Get Servicio By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static ServicioEntity GetOne(int? Clv_Servicio)
        {
            ServicioEntity result = ProviderSoftv.Servicio.GetServicioById(Clv_Servicio);

            return result;
        }

        /// <summary>
        ///Get Servicio By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static ServicioEntity GetOneDeep(int? Clv_Servicio)
        {
            ServicioEntity result = ProviderSoftv.Servicio.GetServicioById(Clv_Servicio);

            return result;
        }



        /// <summary>
        ///Get Servicio
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<ServicioEntity> GetPagedList(int pageIndex, int pageSize)
        {
            SoftvList<ServicioEntity> entities = new SoftvList<ServicioEntity>();
            entities = ProviderSoftv.Servicio.GetPagedList(pageIndex, pageSize);

            return entities ?? new SoftvList<ServicioEntity>();
        }

        /// <summary>
        ///Get Servicio
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<ServicioEntity> GetPagedList(int pageIndex, int pageSize, String xml)
        {
            SoftvList<ServicioEntity> entities = new SoftvList<ServicioEntity>();
            entities = ProviderSoftv.Servicio.GetPagedList(pageIndex, pageSize, xml);

            return entities ?? new SoftvList<ServicioEntity>();
        }


    }




    #region Customs Methods

    #endregion
}
