
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Data;
    using System.ComponentModel;
    using System.Linq;
    using Softv.Providers;
    using Softv.Entities;
    using Globals;

    /// <summary>
    /// Class                   : Softv.BAL.Client.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : tblClasificacionProblemaBussines
    /// File                    : tblClasificacionProblemaBussines.cs
    /// Creation date           : 08/06/2016
    /// Creation time           : 10:52 a. m.
    ///</summary>
    namespace Softv.BAL
    {

    [DataObject]
    [Serializable]
    public class tblClasificacionProblema
    {

    #region Constructors
    public tblClasificacionProblema(){}
    #endregion

    /// <summary>
    ///Adds tblClasificacionProblema
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Insert, true)]
    public static int Add(tblClasificacionProblemaEntity objtblClasificacionProblema)
  {
  int result = ProviderSoftv.tblClasificacionProblema.AddtblClasificacionProblema(objtblClasificacionProblema);
    return result;
    }

    /// <summary>
    ///Delete tblClasificacionProblema
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Delete, true)]
    public static int Delete(long? clvProblema)
    {
    int resultado = ProviderSoftv.tblClasificacionProblema.DeletetblClasificacionProblema(clvProblema);
    return resultado;
    }

    /// <summary>
    ///Update tblClasificacionProblema
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Update, true)]
    public static int Edit(tblClasificacionProblemaEntity objtblClasificacionProblema)
    {
    int result = ProviderSoftv.tblClasificacionProblema.EdittblClasificacionProblema(objtblClasificacionProblema);
    return result;
    }

    /// <summary>
    ///Get tblClasificacionProblema
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Select, true)]
    public static List<tblClasificacionProblemaEntity> GetAll()
    {
    List<tblClasificacionProblemaEntity> entities = new List<tblClasificacionProblemaEntity> ();
    entities = ProviderSoftv.tblClasificacionProblema.GettblClasificacionProblema();
    
    return entities ?? new List<tblClasificacionProblemaEntity>();
    }

    /// <summary>
    ///Get tblClasificacionProblema List<lid>
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Select, true)]
    public static List<tblClasificacionProblemaEntity> GetAll(List<int> lid)
    {
    List<tblClasificacionProblemaEntity> entities = new List<tblClasificacionProblemaEntity> ();
    entities = ProviderSoftv.tblClasificacionProblema.GettblClasificacionProblema(lid);    
    return entities ?? new List<tblClasificacionProblemaEntity>();
    }

    /// <summary>
    ///Get tblClasificacionProblema By Id
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Select)]
    public static tblClasificacionProblemaEntity GetOne(long? clvProblema)
    {
    tblClasificacionProblemaEntity result = ProviderSoftv.tblClasificacionProblema.GettblClasificacionProblemaById(clvProblema);
    
    return result;
    }

    /// <summary>
    ///Get tblClasificacionProblema By Id
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Select)]
    public static tblClasificacionProblemaEntity GetOneDeep(long? clvProblema)
    {
    tblClasificacionProblemaEntity result = ProviderSoftv.tblClasificacionProblema.GettblClasificacionProblemaById(clvProblema);
    
    return result;
    }
    

    
      /// <summary>
      ///Get tblClasificacionProblema
      ///</summary>
    [DataObjectMethod(DataObjectMethodType.Select, true)]
    public static SoftvList<tblClasificacionProblemaEntity> GetPagedList(int pageIndex, int pageSize)
    {
    SoftvList<tblClasificacionProblemaEntity> entities = new SoftvList<tblClasificacionProblemaEntity>();
    entities = ProviderSoftv.tblClasificacionProblema.GetPagedList(pageIndex, pageSize);
    
    return entities ?? new SoftvList<tblClasificacionProblemaEntity>();
    }

    /// <summary>
    ///Get tblClasificacionProblema
    ///</summary>
    [DataObjectMethod(DataObjectMethodType.Select, true)]
    public static SoftvList<tblClasificacionProblemaEntity> GetPagedList(int pageIndex, int pageSize,String xml)
    {
    SoftvList<tblClasificacionProblemaEntity> entities = new SoftvList<tblClasificacionProblemaEntity>();
    entities = ProviderSoftv.tblClasificacionProblema.GetPagedList(pageIndex, pageSize,xml);
    
    return entities ?? new SoftvList<tblClasificacionProblemaEntity>();
    }


    }




    #region Customs Methods
    
    #endregion
    }
  