
using System;
using System.Text;
using System.Data;
using System.Collections.Generic;
using System.Configuration;
using System.Runtime.Remoting;
using Softv.Entities;
using SoftvConfiguration;
using Globals;

namespace Softv.Providers
{
    /// <summary>
    /// Class                   : Softv.Providers.CVECOLCIUProvider
    /// Generated by            : Class Generator (c) 2014
    /// Description             : CVECOLCIU Provider
    /// File                    : CVECOLCIUProvider.cs
    /// Creation date           : 20/05/2016
    /// Creation time           : 06:39 p. m.
    /// </summary>
    public abstract class CVECOLCIUProvider : Globals.DataAccess
    {

        /// <summary>
        /// Instance of CVECOLCIU from DB
        /// </summary>
        private static CVECOLCIUProvider _Instance = null;

        private static ObjectHandle obj;
        /// <summary>
        /// Generates a CVECOLCIU instance
        /// </summary>
        public static CVECOLCIUProvider Instance
        {
            get
            {
                if (_Instance == null)
                {
                    obj = Activator.CreateInstance(
                    SoftvSettings.Settings.CVECOLCIU.Assembly,
                    SoftvSettings.Settings.CVECOLCIU.DataClass);
                    _Instance = (CVECOLCIUProvider)obj.Unwrap();
                }
                return _Instance;
            }
        }

        /// <summary>
        /// Provider's default constructor
        /// </summary>
        public CVECOLCIUProvider()
        {
        }
        /// <summary>
        /// Abstract method to add CVECOLCIU
        ///  /summary>
        /// <param name="CVECOLCIU"></param>
        /// <returns></returns>
        public abstract int AddCVECOLCIU(CVECOLCIUEntity entity_CVECOLCIU);

        /// <summary>
        /// Abstract method to delete CVECOLCIU
        /// </summary>
        public abstract int DeleteCVECOLCIU(int? Clv_Ciudad);

        /// <summary>
        /// Abstract method to update CVECOLCIU
        /// </summary>
        public abstract int EditCVECOLCIU(CVECOLCIUEntity entity_CVECOLCIU);

        /// <summary>
        /// Abstract method to get all CVECOLCIU
        /// </summary>
        public abstract List<CVECOLCIUEntity> GetCVECOLCIU();

        /// <summary>
        /// Abstract method to get all CVECOLCIU List<int> lid
        /// </summary>
        public abstract List<CVECOLCIUEntity> GetCVECOLCIU(List<int> lid);

        /// <summary>
        /// Abstract method to get by id
        /// </summary>
        public abstract CVECOLCIUEntity GetCVECOLCIUById(int? Clv_Ciudad);



        public abstract CVECOLCIUEntity GetCVECOLCIUByCiudad(int? Clv_Ciudad);



        public abstract List<CVECOLCIUEntity> GetCVECOLCIUByClv_Colonia(int? Clv_Colonia);

        public abstract List<CVECOLCIUEntity> GetCVECOLCIUByClv_Ciudad(int? Clv_Ciudad);


        /// <summary>
        ///Get CVECOLCIU
        ///</summary>
        public abstract SoftvList<CVECOLCIUEntity> GetPagedList(int pageIndex, int pageSize);

        /// <summary>
        ///Get CVECOLCIU
        ///</summary>
        public abstract SoftvList<CVECOLCIUEntity> GetPagedList(int pageIndex, int pageSize, String xml);

        /// <summary>
        /// Converts data from reader to entity
        /// </summary>
        protected virtual CVECOLCIUEntity GetCVECOLCIUFromReader(IDataReader reader)
        {
            CVECOLCIUEntity entity_CVECOLCIU = null;
            try
            {
                entity_CVECOLCIU = new CVECOLCIUEntity();
                entity_CVECOLCIU.Clv_Colonia = (int?)(GetFromReader(reader, "Clv_Colonia"));
                entity_CVECOLCIU.Clv_Ciudad = (int?)(GetFromReader(reader, "Clv_Ciudad"));

            }
            catch (Exception ex)
            {
                throw new Exception("Error converting CVECOLCIU data to entity", ex);
            }
            return entity_CVECOLCIU;
        }

    }

    #region Customs Methods

    #endregion
}

