
    using System;
    using System.Text;
    using System.Data;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Runtime.Remoting;
    using Softv.Entities;
    using SoftvConfiguration;
    using Globals;

    namespace Softv.Providers
    {
    /// <summary>
    /// Class                   : Softv.Providers.DatoFiscalProvider
    /// Generated by            : Class Generator (c) 2014
    /// Description             : DatoFiscal Provider
    /// File                    : DatoFiscalProvider.cs
    /// Creation date           : 04/05/2016
    /// Creation time           : 01:31 p. m.
    /// </summary>
    public abstract class DatoFiscalProvider : Globals.DataAccess
    {

    /// <summary>
    /// Instance of DatoFiscal from DB
    /// </summary>
    private static DatoFiscalProvider _Instance = null;

    private static ObjectHandle obj;
    /// <summary>
    /// Generates a DatoFiscal instance
    /// </summary>
    public static DatoFiscalProvider Instance
    {
    get
    {
    if (_Instance == null)
    {
    obj = Activator.CreateInstance(
    SoftvSettings.Settings.DatoFiscal.Assembly,
    SoftvSettings.Settings.DatoFiscal.DataClass);
    _Instance = (DatoFiscalProvider)obj.Unwrap();
    }
    return _Instance;
    }
    }

    /// <summary>
    /// Provider's default constructor
    /// </summary>
    public DatoFiscalProvider()
    {
    }
    /// <summary>
    /// Abstract method to add DatoFiscal
    ///  /summary>
    /// <param name="DatoFiscal"></param>
    /// <returns></returns>
    public abstract int AddDatoFiscal(DatoFiscalEntity entity_DatoFiscal);

    /// <summary>
    /// Abstract method to delete DatoFiscal
    /// </summary>
    public abstract int DeleteDatoFiscal(long? Contrato);

    /// <summary>
    /// Abstract method to update DatoFiscal
    /// </summary>
    public abstract int EditDatoFiscal(DatoFiscalEntity entity_DatoFiscal);

    /// <summary>
    /// Abstract method to get all DatoFiscal
    /// </summary>
    public abstract List<DatoFiscalEntity> GetDatoFiscal();

    /// <summary>
    /// Abstract method to get all DatoFiscal List<int> lid
    /// </summary>
    public abstract List<DatoFiscalEntity> GetDatoFiscal(List<int> lid);

    /// <summary>
    /// Abstract method to get by id
    /// </summary>
    public abstract DatoFiscalEntity GetDatoFiscalById(long? Contrato);

    

    /// <summary>
    ///Get DatoFiscal
    ///</summary>
    public abstract SoftvList<DatoFiscalEntity> GetPagedList(int pageIndex, int pageSize);

    /// <summary>
    ///Get DatoFiscal
    ///</summary>
    public abstract SoftvList<DatoFiscalEntity> GetPagedList(int pageIndex, int pageSize,String xml);

    /// <summary>
    /// Converts data from reader to entity
    /// </summary>
    protected virtual DatoFiscalEntity GetDatoFiscalFromReader(IDataReader reader)
    {
    DatoFiscalEntity entity_DatoFiscal = null;
    try
    {
      entity_DatoFiscal = new DatoFiscalEntity();
    entity_DatoFiscal.Contrato = (long?)(GetFromReader(reader,"Contrato"));
          entity_DatoFiscal.IVADESGLOSADO = (byte?)(GetFromReader(reader,"IVADESGLOSADO"));
          entity_DatoFiscal.RAZON_SOCIAL = (String)(GetFromReader(reader,"RAZON_SOCIAL", IsString : true));
        entity_DatoFiscal.RFC = (String)(GetFromReader(reader,"RFC", IsString : true));
        entity_DatoFiscal.CALLE_RS = (String)(GetFromReader(reader,"CALLE_RS", IsString : true));
        entity_DatoFiscal.NUMERO_RS = (String)(GetFromReader(reader,"NUMERO_RS", IsString : true));
        entity_DatoFiscal.ENTRECALLES = (String)(GetFromReader(reader,"ENTRECALLES", IsString : true));
        entity_DatoFiscal.COLONIA_RS = (String)(GetFromReader(reader,"COLONIA_RS", IsString : true));
        entity_DatoFiscal.CIUDAD_RS = (String)(GetFromReader(reader,"CIUDAD_RS", IsString : true));
        entity_DatoFiscal.ESTADO_RS = (String)(GetFromReader(reader,"ESTADO_RS", IsString : true));
        entity_DatoFiscal.CP_RS = (String)(GetFromReader(reader,"CP_RS", IsString : true));
        entity_DatoFiscal.TELEFONO_RS = (String)(GetFromReader(reader,"TELEFONO_RS", IsString : true));
        entity_DatoFiscal.FAX_RS = (String)(GetFromReader(reader,"FAX_RS", IsString : true));
        entity_DatoFiscal.TIPO = (char)(GetFromReader(reader,"TIPO"));
          entity_DatoFiscal.IDENTIFICADOR = (Decimal?)(GetFromReader(reader,"IDENTIFICADOR"));
          entity_DatoFiscal.CURP = (String)(GetFromReader(reader,"CURP", IsString : true));
        entity_DatoFiscal.id_asociado = (int?)(GetFromReader(reader,"id_asociado"));
          
    }
    catch (Exception ex)
    {
    throw new Exception("Error converting DatoFiscal data to entity", ex);
    }
    return entity_DatoFiscal;
    }
    
    }

    #region Customs Methods
    
    #endregion
    }

  