
using System;
using System.Text;
using System.Data;
using System.Collections.Generic;
using System.Configuration;
using System.Runtime.Remoting;
using Softv.Entities;
using SoftvConfiguration;
using Globals;

namespace Softv.Providers
{
    /// <summary>
    /// Class                   : Softv.Providers.RelPreguntaEncuestasProvider
    /// Generated by            : Class Generator (c) 2014
    /// Description             : RelPreguntaEncuestas Provider
    /// File                    : RelPreguntaEncuestasProvider.cs
    /// Creation date           : 27/04/2016
    /// Creation time           : 05:18 p. m.
    /// </summary>
    public abstract class RelPreguntaEncuestasProvider : Globals.DataAccess
    {

        /// <summary>
        /// Instance of RelPreguntaEncuestas from DB
        /// </summary>
        private static RelPreguntaEncuestasProvider _Instance = null;

        private static ObjectHandle obj;
        /// <summary>
        /// Generates a RelPreguntaEncuestas instance
        /// </summary>
        public static RelPreguntaEncuestasProvider Instance
        {
            get
            {
                if (_Instance == null)
                {
                    obj = Activator.CreateInstance(
                    SoftvSettings.Settings.RelPreguntaEncuestas.Assembly,
                    SoftvSettings.Settings.RelPreguntaEncuestas.DataClass);
                    _Instance = (RelPreguntaEncuestasProvider)obj.Unwrap();
                }
                return _Instance;
            }
        }

        /// <summary>
        /// Provider's default constructor
        /// </summary>
        public RelPreguntaEncuestasProvider()
        {
        }
        /// <summary>
        /// Abstract method to add RelPreguntaEncuestas
        ///  /summary>
        /// <param name="RelPreguntaEncuestas"></param>
        /// <returns></returns>
        public abstract int AddRelPreguntaEncuestas(RelPreguntaEncuestasEntity entity_RelPreguntaEncuestas);

        /// <summary>
        /// Abstract method to delete RelPreguntaEncuestas
        /// </summary>
        public abstract int DeleteRelPreguntaEncuestas(int? IdPregunta);

        /// <summary>
        /// Abstract method to update RelPreguntaEncuestas
        /// </summary>
        public abstract int EditRelPreguntaEncuestas(RelPreguntaEncuestasEntity entity_RelPreguntaEncuestas);

        /// <summary>
        /// Abstract method to get all RelPreguntaEncuestas
        /// </summary>
        public abstract List<RelPreguntaEncuestasEntity> GetRelPreguntaEncuestas();

        /// <summary>
        /// Abstract method to get all RelPreguntaEncuestas List<int> lid
        /// </summary>
        public abstract List<RelPreguntaEncuestasEntity> GetRelPreguntaEncuestas(List<int> lid);

        /// <summary>
        /// Abstract method to get by id
        /// </summary>
        public abstract RelPreguntaEncuestasEntity GetRelPreguntaEncuestasById(int? IdPregunta);


        public abstract List<RelPreguntaEncuestasEntity> GetRelPreguntaEncuestasByIdPregunta(int? IdPregunta);

        public abstract List<RelPreguntaEncuestasEntity> GetRelPreguntaEncuestasByIdEncuesta(int? IdEncuesta);


        /// <summary>
        ///Get RelPreguntaEncuestas
        ///</summary>
        public abstract SoftvList<RelPreguntaEncuestasEntity> GetPagedList(int pageIndex, int pageSize);

        /// <summary>
        ///Get RelPreguntaEncuestas
        ///</summary>
        public abstract SoftvList<RelPreguntaEncuestasEntity> GetPagedList(int pageIndex, int pageSize, String xml);

        /// <summary>
        /// Converts data from reader to entity
        /// </summary>
        protected virtual RelPreguntaEncuestasEntity GetRelPreguntaEncuestasFromReader(IDataReader reader)
        {
            RelPreguntaEncuestasEntity entity_RelPreguntaEncuestas = null;
            try
            {
                entity_RelPreguntaEncuestas = new RelPreguntaEncuestasEntity();
                entity_RelPreguntaEncuestas.IdPregunta = (int?)(GetFromReader(reader, "IdPregunta"));
                entity_RelPreguntaEncuestas.IdEncuesta = (int?)(GetFromReader(reader, "IdEncuesta"));

            }
            catch (Exception ex)
            {
                throw new Exception("Error converting RelPreguntaEncuestas data to entity", ex);
            }
            return entity_RelPreguntaEncuestas;
        }

    }

    #region Customs Methods

    #endregion
}

