
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    namespace Softv.Entities
    {
    /// <summary>
    /// Class                   : Softv.Entities.BusquedaIndividualEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : BusquedaIndividual entity
    /// File                    : BusquedaIndividualEntity.cs
    /// Creation date           : 01/06/2016
    /// Creation time           : 11:39 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class BusquedaIndividualEntity : BaseEntity
    {
    #region Attributes
    
      /// <summary>
      /// Property Id
      /// </summary>
      [DataMember]
      public int? Id { get; set; }
      /// <summary>
      /// Property Contrato
      /// </summary>
      [DataMember]
      public int? Contrato { get; set; }
      /// <summary>
      /// Property Nombre
      /// </summary>
      [DataMember]
      public String Nombre { get; set; }
      /// <summary>
      /// Property Telefono
      /// </summary>
      [DataMember]
      public String Telefono { get; set; }
      /// <summary>
      /// Property Celular
      /// </summary>
      [DataMember]
      public String Celular { get; set; }
      /// <summary>
      /// Property Calle
      /// </summary>
      [DataMember]
      public String Calle { get; set; }
      /// <summary>
      /// Property Numero
      /// </summary>
      [DataMember]
      public String Numero { get; set; }
      /// <summary>
      /// Property Colonia
      /// </summary>
      [DataMember]
      public String Colonia { get; set; }
      /// <summary>
      /// Property Ciudad
      /// </summary>
      [DataMember]
      public String Ciudad { get; set; }
    #endregion
    }
    }

  