
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    namespace Softv.Entities
    {
    /// <summary>
    /// Class                   : Softv.Entities.CiudadServidorEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : CiudadServidor entity
    /// File                    : CiudadServidorEntity.cs
    /// Creation date           : 02/08/2016
    /// Creation time           : 12:53 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class CiudadServidorEntity : BaseEntity
    {
    #region Attributes
    
      /// <summary>
      /// Property Id
      /// </summary>
      [DataMember]
      public int? Id { get; set; }
      /// <summary>
      /// Property Ciudad
      /// </summary>
      [DataMember]
      public String Ciudad { get; set; }
      /// <summary>
      /// Property IdPlaza
      /// </summary>
      [DataMember]
      public int? IdPlaza { get; set; }
          [DataMember]
          public ConexionEntity Conexion { get; set; }
        
    #endregion
    }
    }

  