
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    namespace Softv.Entities
    {
    /// <summary>
    /// Class                   : Softv.Entities.RelPreguntaOpcMultsEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : RelPreguntaOpcMults entity
    /// File                    : RelPreguntaOpcMultsEntity.cs
    /// Creation date           : 27/04/2016
    /// Creation time           : 05:19 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class RelPreguntaOpcMultsEntity : BaseEntity
    {
    #region Attributes
    
      /// <summary>
      /// Property IdPregunta
      /// </summary>
      [DataMember]
      public int? IdPregunta { get; set; }
      /// <summary>
      /// Property Id_ResOpcMult
      /// </summary>
      [DataMember]
      public int? Id_ResOpcMult { get; set; }
          [DataMember]
          public PreguntaEntity Pregunta { get; set; }
        
          [DataMember]
          public ResOpcMultsEntity ResOpcMults { get; set; }
        
    #endregion
    }
    }

  