
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Softv.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.TapEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : Tap entity
    /// File                    : TapEntity.cs
    /// Creation date           : 04/05/2016
    /// Creation time           : 01:31 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class TapEntity : BaseEntity
    {
        #region Attributes

        /// <summary>
        /// Property IdTap
        /// </summary>
        [DataMember]
        public int? IdTap { get; set; }
        /// <summary>
        /// Property Clv_Sector
        /// </summary>
        [DataMember]
        public int? Clv_Sector { get; set; }
        /// <summary>
        /// Property Clv_Colonia
        /// </summary>
        [DataMember]
        public int? Clv_Colonia { get; set; }
        /// <summary>
        /// Property Clv_Calle
        /// </summary>
        [DataMember]
        public int? Clv_Calle { get; set; }
        /// <summary>
        /// Property IdPoste
        /// </summary>
        [DataMember]
        public int? IdPoste { get; set; }
        /// <summary>
        /// Property Ingenieria
        /// </summary>
        [DataMember]
        public int? Ingenieria { get; set; }
        /// <summary>
        /// Property Salidas
        /// </summary>
        [DataMember]
        public int? Salidas { get; set; }
        /// <summary>
        /// Property Clave
        /// </summary>
        [DataMember]
        public String Clave { get; set; }
        /// <summary>
        /// Property NoCasas
        /// </summary>
        [DataMember]
        public int? NoCasas { get; set; }
        /// <summary>
        /// Property NoNegocios
        /// </summary>
        [DataMember]
        public int? NoNegocios { get; set; }
        /// <summary>
        /// Property NoLotes
        /// </summary>
        [DataMember]
        public int? NoLotes { get; set; }
        /// <summary>
        /// Property NoServicios
        /// </summary>
        [DataMember]
        public int? NoServicios { get; set; }
        /// <summary>
        /// Property FrenteANumero
        /// </summary>
        [DataMember]
        public String FrenteANumero { get; set; }
        #endregion
    }
}

